### ISSUE TITLE
Codefehler/verbesserung

### ISSUE THREAD

**Issue by Puckbeisser** [CloudImagesAreTheBest/VendingMachineC#27]
Aus der Pruefzahl muss das cout<<Pruefzahl; noch entfernt werden. Der Kunde soll die Pruefahl ja nicht sehen können.

Geldeinwurf springt nicht aus der Schleife, wenn der Muenzeinwurf gleich der Geldforderung ist.

Funktion CalcRestCoin bitte umbennen in CalcChange

Gibt man bei der "Kaffeeauswahl" etwas Falsches ein erscheint zwar die Ausgabe "Zurück zum Hauptmenu" aber das Programm läuft einfach normal weiter.

**Comment by PierreGlicinski** [comment]
Pro Fehler 1 Ticket =P Aber wird gemacht

**Comment by PierreGlicinski** [comment]
1.) Fertig
2.) Fertig
3.) Abgewiesen
4. Fertig
